---
- name: "netdata | Deploy conf.d/fping.conf"
  template:
    src: "conf.d/fping.j2"
    dest: "{{ hostvars[inventory_hostname]['netdata_plugins_conf_dest'] +
      '/fping.conf' }}"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  notify:
    - "Restart netdata"
