---
- name: netdata | Deploy netdata.conf
  ansible.builtin.template:
    src: "netdata.j2"
    dest: "{{ hostvars[inventory_hostname]['netdata_dest'] + '/' +
              'netdata.conf' }}"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  when:
  - "vars['netdata_settings'] is defined"
  - "vars['netdata_settings'] != []"
  notify:
  - "Restart netdata"
- name: netdata | Enable netdata
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['netdata_service'] }}"
    enabled: "yes"
  when:
  - "hostvars[inventory_hostname]['netdata'] is defined"
  - "hostvars[inventory_hostname]['netdata'] != ''"
  - "hostvars[inventory_hostname]['netdata'] |
     community.general.json_query(vars['netdata_enable']) is defined"
  - "hostvars[inventory_hostname]['netdata'] |
     community.general.json_query(vars['netdata_enable']) == 'true'"
  vars:
    netdata_enable: "[] | map(&enable || 'false', @) | [0]"
