---
- ansible.builtin.include_tasks:
    file: "deploy_python.d_settings.yml"
  when:
    - "vars['netdata_plugins_settings_python']['local'] is defined"
    - "vars['netdata_plugins_settings_python']['local'] != ''"
- ansible.builtin.include_tasks:
    file: "conf.d/python.d/smartd_log.yml"
  when:
    - "vars['netdata_plugins_settings_python']['smartd_log'] is defined"
    - "vars['netdata_plugins_settings_python']['smartd_log'] != ''"
- ansible.builtin.include_tasks:
    file: "conf.d/python.d/nginx.yml"
  when:
    - "vars['netdata_plugins_settings_python']['nginx'] is defined"
    - "vars['netdata_plugins_settings_python']['nginx'] != ''"
- ansible.builtin.include_tasks:
    file: "conf.d/plugin.d/fping.yml"
  when:
    - "vars['netdata_plugins_settings_plugind']['fping'] is defined"
    - "vars['netdata_plugins_settings_plugind']['fping'] != ''"
