---
- name: "netdata | Include python.d.conf tasks"
  ansible.builtin.include_tasks:
    file: "deploy_python.d_settings.yml"
  when:
    - "vars['netdata_plugins_settings_python']['local'] is defined"
    - "vars['netdata_plugins_settings_python']['local'] != ''"
- name: "netdata | Include go.d.conf tasks"
  ansible.builtin.include_tasks:
    file: "deploy_go.d_settings.yml"
  when:
    - "vars['netdata_plugins_settings_golang']['local'] is defined"
    - "vars['netdata_plugins_settings_golang']['local'] != ''"
    - "vars['netdata_plugins_settings_golang']['local'] != []"
- name: "netdata | Include python.d/nginx.conf tasks"
  ansible.builtin.include_tasks:
    file: "go.d/ping.yml"
  vars:
    netdata_plugins_settings_golang_ping_jobs:
      jobs: "{{ vars['netdata_plugins_settings_golang']['ping'] }}"
  when:
    - "vars['netdata_plugins_settings_golang']['ping'] is defined"
    - "vars['netdata_plugins_settings_golang']['ping'] != ''"
    - "vars['netdata_plugins_settings_golang']['ping'] != []"
