---
- name: "netdata | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "netdata | Include packages tasks"
  ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['netdata'] is defined"
    - "hostvars[inventory_hostname]['netdata'] != ''"
    - "hostvars[inventory_hostname]['netdata'] |
       community.general.json_query(vars['netdata_install_package']) is defined"
    - "hostvars[inventory_hostname]['netdata'] |
       community.general.json_query(vars['netdata_install_package']) == 'true'"
  vars:
    netdata_install_package: "[] | map(&install_package || 'false', @) | [0]"
- name: "netdata | Include exporting settings tasks"
  ansible.builtin.include_tasks:
    file: "deploy_exporting_settings.yml"
  when:
    - "vars['netdata_exporting_settings'] is defined"
    - "vars['netdata_exporting_settings'] != []"
- name: "netdata | Include plugins settings tasks"
  ansible.builtin.include_tasks:
    file: "deploy_plugins_settings.yml"
  when:
    - "vars['netdata_plugins_settings'] is defined"
    - "vars['netdata_plugins_settings'] != []"
- name: "netdata | Include deployment tasks"
  ansible.builtin.import_tasks:
    file: "deploy_netdata.yml"
