---
- include_tasks: pre_requisite.yml
- include_tasks: packages.yml
  when:
  - "hostvars[inventory_hostname]['netdata_install_packages'] is defined"
  - "hostvars[inventory_hostname]['netdata_install_packages'] == 'true'"
- include_tasks: deploy_netdata.yml
  when:
  - "hostvars[inventory_hostname]['netdata'] is defined"
  - "hostvars[inventory_hostname]['netdata'] != ''"
