---
- import_tasks: "pre_requisite.yml"
- include_tasks: "packages.yml"
  when:
  - "hostvars[inventory_hostname]['netdata_install_packages'] is defined"
  - "hostvars[inventory_hostname]['netdata_install_packages'] == 'true'"
- import_tasks: "deploy_netdata.yml"
- import_tasks: "deploy_plugins_settings.yml"
