---
- name: netdata | Install the required packages in Redhat derivatives
  block:
  - name: netdata | Install the required packages for RedHat via yum
    yum:
      name: "{{ hostvars[inventory_hostname]['netdata_package'] }}"
      state: "{{ hostvars[inventory_hostname]['netdata_package_state'] |
                 default(omit) }}"
      update_cache: "yes"
    when:
    - "hostvars[inventory_hostname]['ansible_pkg_mgr'] == 'yum'"
  - name: netdata | Install the required packages for RedHat via dnf
    dnf:
      name: "{{ hostvars[inventory_hostname]['netdata_package'] }}"
      state: "{{ hostvars[inventory_hostname]['netdata_package_state'] |
                 default(omit) }}"
      update_cache: "yes"
    when:
    - "hostvars[inventory_hostname]['ansible_pkg_mgr'] == 'dnf'"
  when:
  - "hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'"
- name: netdata | Install the required packages in Debian derivatives
  apt:
    name: "{{ hostvars[inventory_hostname]['netdata_package'] }}"
    state: "{{ hostvars[inventory_hostname]['netdata_package_state'] |
               default(omit) }}"
    update_cache: "yes"
  when:
  - "hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'"
- name: netdata | Install the required packages in ArchLinux derivatives
  pacman:
    name: "{{ hostvars[inventory_hostname]['netdata_package'] }}"
    state: "{{ hostvars[inventory_hostname]['netdata_package_state'] |
               default(omit) }}"
    update_cache: "yes"
  when:
  - "hostvars[inventory_hostname]['ansible_os_family'] == 'Archlinux'"
