---
- name: netdata | Assert that netdata package state in valid value
  assert:
    that:
    - "hostvars[inventory_hostname]['netdata_package_state'] in
       ['present', 'latest']"
    msg: "'netdata_package_state' must be in 'present' or 'latest'."
    quiet: "true"
  when:
  - "hostvars[inventory_hostname]['netdata_package_state'] is defined"
- name: netdata | Add the OS specific varibles
  include_vars: "{{ hostvars[inventory_hostname]['ansible_os_family'] +
                    '.yml' }}"
- name: netdata | Set facts about netdata role
  set_fact:
    netdata_settings: "{{ hostvars[inventory_hostname]['netdata'] |
      json_query('[].netdata_settings[]') }}"
    netdata_plugins_settings:
      "{{ hostvars[inventory_hostname]['netdata'] |
      json_query('[].plugins_settings[]') }}"
    netdata_plugins_settings_python:
      "{{ hostvars[inventory_hostname]['netdata'] |
      json_query('[].plugins_settings[].python[] | [0]') }}"
- name: netdata | Create catalogs
  file:
    path: "{{ hostvars[inventory_hostname]['netdata_dest'] }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  when:
  - "hostvars[inventory_hostname]['netdata'] is defined"
  - "hostvars[inventory_hostname]['netdata'] != ''"
