---
- name: Restart netdata
  systemd:
    name: "{{ hostvars[inventory_hostname]['netdata_service'] }}"
    state: "restarted"
  when:
  - "hostvars[inventory_hostname]['netdata_restart'] is defined"
  - "hostvars[inventory_hostname]['netdata_restart'] == 'true'"
