---
- name: "netdata | Deploy conf.d/python.d/nginx.conf"
  ansible.builtin.template:
    src: "conf.d/python.d/nginx.j2"
    dest: "{{ hostvars[inventory_hostname]['netdata_plugins_conf_dest'] +
      '/python.d/nginx.conf' }}"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  notify:
    - "Restart netdata"
