---
- name: "netdata | Deploy exporting.conf"
  ansible.builtin.template:
    src: "exporting.conf.j2"
    dest: "{{ hostvars[inventory_hostname]['netdata_dest'] +
      '/exporting.conf' }}"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  notify:
    - "Restart netdata"
