---
- name: "netdata | Deploy go.d.conf"
  ansible.builtin.template:
    src: "go.d.conf.j2"
    dest: "{{ hostvars[inventory_hostname]['netdata_dest'] + '/go.d.conf' }}"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  notify:
    - "Restart netdata"
