---
- name: "netdata | Include python.d.conf tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/python.d_settings.yml"
  when:
    - "vars['netdata_plugins_settings_python']['local'] is defined"
    - "vars['netdata_plugins_settings_python']['local'] != ''"
- name: "netdata | Include go.d.conf tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/go.d_settings.yml"
  when:
    - "vars['netdata_plugins_settings_golang']['local'] is defined"
    - "vars['netdata_plugins_settings_golang']['local'] != ''"
    - "vars['netdata_plugins_settings_golang']['local'] != []"
- name: "netdata | Include go.d/ping.conf tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/go.d/ping.yml"
  vars:
    netdata_plugins_settings_golang_ping_jobs:
      jobs: "{{ vars['netdata_plugins_settings_golang']['ping'] }}"
  when:
    - "vars['netdata_plugins_settings_golang']['ping'] is defined"
    - "vars['netdata_plugins_settings_golang']['ping'] != ''"
    - "vars['netdata_plugins_settings_golang']['ping'] != []"
- name: "netdata | Include go.d/storcli.conf tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/go.d/storcli.yml"
  vars:
    netdata_plugins_settings_golang_storcli_jobs:
      jobs: "{{ vars['netdata_plugins_settings_golang']['storcli'] }}"
  when:
    - "vars['netdata_plugins_settings_golang']['storcli'] is defined"
    - "vars['netdata_plugins_settings_golang']['storcli'] != ''"
    - "vars['netdata_plugins_settings_golang']['storcli'] != []"
- name: "netdata | Include go.d/adaptec_raid.conf tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/go.d/adaptec_raid.yml"
  vars:
    netdata_plugins_settings_golang_adaptec_raid_jobs:
      jobs: "{{ vars['netdata_plugins_settings_golang']['adaptec_raid'] }}"
  when:
    - "vars['netdata_plugins_settings_golang']['adaptec_raid'] is defined"
    - "vars['netdata_plugins_settings_golang']['adaptec_raid'] != ''"
    - "vars['netdata_plugins_settings_golang']['adaptec_raid'] != []"
- name: "netdata | Include go.d/apcupsd.conf tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/go.d/apcupsd.yml"
  vars:
    netdata_plugins_settings_golang_apcupsd_jobs:
      jobs: "{{ vars['netdata_plugins_settings_golang']['apcupsd'] }}"
  when:
    - "vars['netdata_plugins_settings_golang']['apcupsd'] is defined"
    - "vars['netdata_plugins_settings_golang']['apcupsd'] != ''"
    - "vars['netdata_plugins_settings_golang']['apcupsd'] != []"
