---
- name: "netdata | Deploy conf.d/charts.d/apcupsd.conf"
  ansible.builtin.template:
    src: "charts.d/apcupsd.j2"
    dest: "{{ hostvars[inventory_hostname]['netdata_dest'] +
      '/charts.d/apcupsd.conf' }}"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  notify:
    - "Restart netdata"
